name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: vedantkakde/wisecow-app:latest

  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Kubernetes
        run: |
          echo "$KUBE_CONFIG" > kubeconfig.yaml
          kubectl config set-context my-context --cluster=my-cluster --user=my-user
          kubectl config use-context my-context
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml service.yaml
